version: '2'
services:
  # Le serveur MySQL avec les données NOREV
  db:
    container_name: norev_db
    image: rothgar/rpi-mysql:5.5
    ports:
      - "13306:3306"
    env_file: db.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: always

  app:
    container_name: norev_app
    # pour construire l'image
    build: .
    volumes:
      - .:/myapp
    # pour utiliser l'image
    #image: app
    links:
      - db
    environment:
      SECRET_KEY_BASE: abcdefg
    networks:
      - backend
    restart: always

  web:
    container_name: norev_nginx
    # pour construire l'image
    build:
      context: .
      dockerfile: Dockerfile-nginx
    # pour utiliser l'image
    #image: web
    links:
      - app
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    restart: always

  #adminer:
  #  container_name: norev_adminer
  #  image: adminer
  #  ports:
  #    - "8080:8080"
  #  links:
  #    - db
  #  networks:
  #    - frontend
  #    - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
