version: '2'
services:
  # Le serveur MySQL avec les données NOREV
  db:
    container_name: norev_db
    image: mysql
    ports:
      - "13306:3306"
    env_file: db.env
    volumes:
      - db_data:/var/lib/mysql
  
  app:
    container_name: app
    # pour construire l'image
    build: .
    volumes:
      - .:/myapp
    # pour utiliser l'image
    #image: app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      SECRET_KEY_BASE: abcdefg
      VIRTUAL_HOST: beer.docker
      RAILS_ENV: production

  adminer:
    container_name: norev_adminer
    image: adminer
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  db_data:
