version: '3'
services:
  # Le serveur MySQL avec les données NOREV
  db:
    container_name: norev_db
    image: mysql
    ports:
      - "13306:3306"
    env_file: db.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    container_name: app
    # pour construire l'image
    build: .
    volumes:
      - .:/myapp
    # pour utiliser l'image
    #image: app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      SECRET_KEY_BASE: abcdefg
    networks:
      - frontend

  adminer:
    container_name: norev_adminer
    image: adminer
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - frontend
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
