version: '3'
services:
  # Le serveur MySQL avec les données NOREV
  db:
    container_name: norev_db
    image: mysql
    ports:
      - "13306:3306"
    env_file: db.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    container_name: norev_app
    # pour construire l'image
    build:
      context: .
      dockerfile: Dockerfile-alpine
    volumes:
      - .:/myapp
    # pour utiliser l'image
    #image: app
    links:
      - db
    environment:
      SECRET_KEY_BASE: abcdefg
    networks:
      - backend

  web:
    container_name: norev_nginx
    # pour construire l'image
    build:
      context: .
      dockerfile: Dockerfile-nginx
    # pour utiliser l'image
    #image: web
    links:
      - app
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  adminer:
    container_name: norev_adminer
    image: adminer
    ports:
      - "8080:8080"
    links:
      - db
    networks:
      - frontend
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
